# Generated by Django 4.2.1 on 2023-11-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_room_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="uuid",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
