# Generated by Django 4.2.1 on 2023-11-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_room_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="client",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
