# Generated by Django 4.2.1 on 2023-11-18 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0006_alter_room_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
