# Generated by Django 4.2.1 on 2023-11-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_alter_room_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="client",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="room",
            name="uuid",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
