# Generated by Django 4.2.1 on 2023-11-18 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_alter_room_client_alter_room_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="created_by",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="room",
            name="client",
        ),
    ]
