# Generated by Django 4.2.1 on 2023-11-18 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_alter_room_user_roomparticipant_room_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roomparticipant",
            options={
                "default_permissions": [],
                "verbose_name": "Room Participant",
                "verbose_name_plural": "Room Participants",
            },
        ),
        migrations.RemoveField(
            model_name="room",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="room",
            name="user",
        ),
        migrations.AlterModelTable(
            name="roomparticipant",
            table="room_participant",
        ),
    ]
