# Generated by Django 4.2.1 on 2023-11-18 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0011_alter_roomparticipant_options_remove_room_agent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roomparticipant",
            options={
                "default_permissions": [],
                "verbose_name": "Chat Room Participant",
                "verbose_name_plural": "Chat Room Participants",
            },
        ),
        migrations.AlterModelTable(
            name="roomparticipant",
            table="chat_room_participant",
        ),
    ]
