# Generated by Django 4.2.1 on 2023-11-18 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0012_alter_roomparticipant_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
