# Generated by Django 4.2.1 on 2023-11-18 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0013_room_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="sent_by",
        ),
    ]
