// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_DIRECT_CONTACT = "GET_DIRECT_CONTACT";



/* MESSAGES */
export const GET_MESSAGES = "GET_MESSAGES";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL";

export const GET_CHANNELS = "GET_CHANNELS";

// CHAT ROOM 
export const ADD_NEW_CHAT = "ADD_NEW_CHAT";
// export const ADD_NEW_CHAT_SUCCESS = "ADD_NEW_CHAT_SUCCESS";
// export const ADD_NEW_CHAT_FAIL = "ADD_NEW_CHAT_FAIL";

export const ADD_MESSAGE = "ADD_MESSAGE";

export const DELETE_MESSAGE = "DELETE_MESSAGE";
